### ISSUE TITLE
[TODO] Write more Pytest tests for this

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/json-maestro#2]
This really needs more testing written for this application program. The included test is only a starting point.

I'm still learning Pytest. 

This is a TODO action item.

**Comment by shoshta73** [comment]
I have taken a look at tests in currenct form.

I would like add tests that get some data from public apis that server "lorem ipsum" like json data in setup phase and then go and test current data manipulation api

**Comment by gbowne1** [comment]
thats a great idea.

I did a feature thing #18 

I'm still learning pytest

**Comment by gbowne1** [comment]
Closing this todo activity. 

We already now have a number of tests for this.
