### ISSUE TITLE
jsonmaestro.py def remove_comments has unknown types

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/json-maestro#20]
```py
def remove_comments(obj: Union[Dict[str, Any], List[Any], Any]) -> Union[Dict[str, Any], List[Any], Any]:
	"""Remove comments from the object."""
	if isinstance(obj, dict):
		return {k: remove_comments(v) for k, v in obj.items()}
	elif isinstance(obj, list):
		return [remove_comments(item) for item in obj]
	else:
		return obj
```

has partially unknown types for k, v and item in the return, at least according to my Pylance.

**Comment by gbowne1** [comment]
item, key and value also also show unknown or partially unknown types in `def remove_duplicate_keys`

**Comment by shoshta73** [comment]
is this function needed since load_jsonc already removes comments from the source so data can be returned as json?

**Comment by gbowne1** [comment]
@shoshta73 I don't think it's necessary to have duplicate functions
