### ISSUE TITLE
json.load automatically removes duplicate keys in valid json

### ISSUE THREAD

**Issue by shoshta73** [gbowne1/json-maestro#22]
I have notice that when loading json from string 

example:
```json
{
    data: "foo",
    key: "bar",
    data: "baz",
}
```

json.load will automatically put data=baz into the dictionary

**Comment by shoshta73** [comment]
So are we dropping remove_duplicate_keys function out becuase json.load already takes in last instace of the key as final value?

**Comment by gbowne1** [comment]
Well, it should in any particular case, be able to remove any duplicate key unless something could be set in cases where json and jsonc arrays and objects and other permutations of this, to keep it from removing any necessary duplicate item.

I would avoid duplicating functionality.

**Comment by shoshta73** [comment]
Reopening this issue after cheking v8 parser implementation.

So currently as per implentation of AST of javascript, when duplicate keys are encountered in javascript object, no error is reported.
Given that JSON is basically subset of javascripts AST used for representing objects without their respective methods atached it handles duplicate keys in same as used javascript parser does.

So my conclusion is that "duplicate key error" message is just a LSP giving a person warning about having duplicate keys.

In my opinion removing remove_duplicate_keys would resolve this issue.

**Comment by gbowne1** [comment]
we should look into some sort of pythonesque CI/CD.

**Comment by gbowne1** [comment]
I agree with your comments here 100%

**Comment by gbowne1** [comment]
I haven't extensively looked at actions/workflows for Python stuff, but yes.  

This was recommended:

<https://www.youtube.com/watch?v=qznIeQBMTyM>
<https://www.youtube.com/watch?app=desktop&v=WTofttoD2xg>

<https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python>

<https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/>
