### ISSUE TITLE
[QAQC] test/test workflow / action fails 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/json-maestro#26]
The test/test workflow/action fails on PR run

**Comment by shoshta73** [comment]
Im aware of this, trying to figure out how does json.load work, so we can have duplicate keys on load and not just last instance of the key

**Comment by shoshta73** [comment]
So technically speaking, json.loads should then fail to parse when given input with 2 identical key as its not in json spec as per rfc8259?

> We should look at publishing at some point. There appears to be several methods..

Could you reserve the package name possibly?

**Comment by gbowne1** [comment]
I'm just guessing that there could theoretically be a case where there are indeed identical keys, thought I haven't run across anything with that yet. However, I would opt for the case where the duplicated keys were not wanted.  This could potentially be a feature we turn on and off with a option/flag.

Yes the package name could be reserved.
