### ISSUE TITLE
Removing Comment symbols

### ISSUE THREAD

**Issue by shoshta73** [gbowne1/json-maestro#32]
Current implementation of remove_comments function does not take in account comment symbols in strings which should not be treated as comment

**Comment by shoshta73** [comment]
Is it ok if push changes to relevant test files / test data directly to master?

**Comment by gbowne1** [comment]
Non-breaking changes can be pushed directly to master for maintainers/contributors only, especially if the changes have been tested.  I shouldve put that in the contributing doc.  I prefer in PR's to show working changes and possibly diffs.. ie `before and after` the changes as well as passing tests.

**Comment by shoshta73** [comment]
I have pushed updated test file into [tests/comment-symbols](https://github.com/gbowne1/json-maestro/tree/tests/comment-symbols)

**Comment by shoshta73** [comment]
Well this is interesting...

![image](https://github.com/user-attachments/assets/5f6a5a5b-683f-4d4e-ace9-7e102f3950b8)

**Comment by shoshta73** [comment]
I assume maybe filesize over 1MiB could pose a prose a problem

**Comment by gbowne1** [comment]
I am assuming that we are shoving stuff into memory for parsing.  This will get bad with REALLY large files.

alrighty will have a look.

**Comment by shoshta73** [comment]
Large files could also cause object misalignment within python interpreter if they are not chunked wich probably lead to `"/*"` to be treated a comment

**Comment by gbowne1** [comment]
yes, thats true it could. we would need to test this on some really large data.

**Comment by shoshta73** [comment]
So maybe dump like 100 npm dependencies in package.json download them and only store package-lock file to test this?

**Comment by gbowne1** [comment]
Yes, this could go along with [#30](https://github.com/gbowne1/json-maestro/issues/30).

**Comment by gbowne1** [comment]
Have we resolved this?

**Comment by shoshta73** [comment]
Yeah if it happens again we can just reopen the issue
