### ISSUE TITLE
Python toolchain complaining

### ISSUE THREAD

**Issue by shoshta73** [gbowne1/json-maestro#33]
1.
```
running install
/json-maestro/venv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/json-maestro/venv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
```

2.
```
DEPRECATION: Loading egg at /json-maestro/venv/lib/python3.12/site-packages/jsonmaestro-0.0.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
```

**Comment by gbowne1** [comment]
I noticed this too but was unsure of what to do about it

**Comment by gbowne1** [comment]
@shoshta73 

here are some of my thoughts after doing some research and talking to @odatnurd

what I read is that somewhere along the line, setup.py and .egg files in Python packaging got deprecated.

Further reading suggests that the `setuptools` team recommends avoiding direct execution of setup.py and instead using standardized tools like pypa/build, pypa/installer, or other standards-based tools.

.egg files are also considered deprecated.  what about wheel?

Should we build for legacy toolchain too, 3.7~3.9 in a separate manner than we could build for 3.10~3.12?

@loresayer on Twitch said to check lines 40 & 57 of /.github/workflows /[pip-install.yml](https://pip-install.yml/) they use deprecated calls to python [setup.py](https://setup.py/) install (and build)

do we use tox to test across versions? use poetry or flit?

what about virtualenv / venv?

I've never used easy_install..

I saw this in a  google search.. <https://stackoverflow.com/questions/73257839/setup-py-install-is-deprecated-warning-shows-up-every-time-i-open-a-terminal-i>

I've also never used pypa/build or pypa/installer..

**Comment by shoshta73** [comment]
So drop current and follow these?

https://packaging.python.org/en/latest/tutorials/packaging-projects/
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

**Comment by gbowne1** [comment]
@shoshta73 yes, from all of the reading over the weekend.. yes. this is ideally the way we should  go if we are using anything over Python 3.8 especially 3.10~3.10 and any newer package versions that go along with these versions.

If we ship for older toolchains.. well thats a entirely different process from what I can see, but the two would have to be separated and that workflow probably done automatically.
