### ISSUE TITLE
[QOL] Cleanup stale branches

### ISSUE THREAD

**Issue by shoshta73** [gbowne1/json-maestro#39]
We are currently having a bit of a situation with branches, so i would like suggest cleaning up the branches a bit.

Out of currently present branches i think there is no currently present branches to keep.

**Comment by gbowne1** [comment]
@shoshta73 

There is a workflow for this. Its quite a chore to clean up branches.

I think its called Stale Branches in the Action/Workflow Marketplace.

**Comment by shoshta73** [comment]
This [one](https://github.com/marketplace/actions/stale-branches)?

**Comment by gbowne1** [comment]
Yes, thats the one.. there are or were others.

**Comment by shoshta73** [comment]
Closing as it was resolved in #40
