### ISSUE TITLE
HotFix - fix to setup.py

### ISSUE THREAD

**Issue by shoshta73** [gbowne1/json-maestro#9]
I have made mistake of overiding back to template setup.py file in merge request #8.

**Comment by shoshta73** [comment]
[0001-fixup.patch.txt](https://github.com/user-attachments/files/17243968/0001-fixup.patch.txt)

**Comment by gbowne1** [comment]
Yes, please do, Thanks.

**Comment by shoshta73** [comment]
Should I keep patch 0004 for convinience of not messing up someones vscode config?

**Comment by gbowne1** [comment]
sure.
